#pragma once

/************************************************************************************************************************/
namespace SPACE_LIGHT{




/************************************************************
************************************************************/

/******************************
******************************/
static const int W_ColorChange[NUM_STATES][NUM_BOOSTMODE][NUM_COLOR_CHANGE_KEEP] = {
	// STATE_NOSOUND,
	{// Normal{	COLOR_KEEP, COLOR_CHANGE, COLOR_FLASH}, Boost{*, *, *}
		{1, 9, 0}, {1, 9, 0}
	},
	
	// STATE_SOUND,
	{
		{2, 8, 0}, {2, 8, 0}
	},
	// STATE_SOUND_DROP,
	{
	},
	// STATE_BEAT_IN,
	{
		{2, 8, 0}, {2, 8, 0}
	},
	// STATE_BEAT_IN_DROP,
	{
	},
	// STATE_FLYWHEEL,
	{
		{2, 8, 0}, {1, 7, 2}
	},
	// STATE_FLYWHEEL_DROP,
	{
	},

};

/******************************
******************************/
static const int W_BlockGrouping_Tangible[NUM_STATES][NUM_BOOSTMODE][NUM_GROUPTYPES_TANGIBLE] = {
	// STATE_NOSOUND,
	{
		{ // Normal
			1, // "TANGIBLE_GP0__NOSOUND",
			0, // "TANGIBLE_GP0__SOUND",
			0, // "TANGIBLE_GP0__BEAT_NORMAL",
			0, // "TANGIBLE_GP0__BEAT_BOOST",
			0, // "TANGIBLE_GP0__FLYWHEEL_NORMAL",
			0, // "TANGIBLE_GP0__FLYWHEEL_BOOST",
		},
		{ // Boost
		},
	},
	// STATE_SOUND,
	{
		{ // Normal
			0, // "TANGIBLE_GP0__NOSOUND",
			1, // "TANGIBLE_GP0__SOUND",
			0, // "TANGIBLE_GP0__BEAT_NORMAL",
			0, // "TANGIBLE_GP0__BEAT_BOOST",
			0, // "TANGIBLE_GP0__FLYWHEEL_NORMAL",
			0, // "TANGIBLE_GP0__FLYWHEEL_BOOST",
		},
		{ // Boost
			0, // "TANGIBLE_GP0__NOSOUND",
			1, // "TANGIBLE_GP0__SOUND",
			0, // "TANGIBLE_GP0__BEAT_NORMAL",
			0, // "TANGIBLE_GP0__BEAT_BOOST",
			0, // "TANGIBLE_GP0__FLYWHEEL_NORMAL",
			0, // "TANGIBLE_GP0__FLYWHEEL_BOOST",
		},
	},
	// STATE_SOUND_DROP,
	{
	},
	// STATE_BEAT_IN,
	{
		{ // Normal
			0, // "TANGIBLE_GP0__NOSOUND",
			0, // "TANGIBLE_GP0__SOUND",
			1, // "TANGIBLE_GP0__BEAT_NORMAL",
			0, // "TANGIBLE_GP0__BEAT_BOOST",
			0, // "TANGIBLE_GP0__FLYWHEEL_NORMAL",
			0, // "TANGIBLE_GP0__FLYWHEEL_BOOST",
		},
		{ // Boost
			0, // "TANGIBLE_GP0__NOSOUND",
			0, // "TANGIBLE_GP0__SOUND",
			0, // "TANGIBLE_GP0__BEAT_NORMAL",
			1, // "TANGIBLE_GP0__BEAT_BOOST",
			0, // "TANGIBLE_GP0__FLYWHEEL_NORMAL",
			0, // "TANGIBLE_GP0__FLYWHEEL_BOOST",
		},
	},
	// STATE_BEAT_IN_DROP,
	{
	},
	// STATE_FLYWHEEL,
	{
		{ // Normal
			0, // "TANGIBLE_GP0__NOSOUND",
			0, // "TANGIBLE_GP0__SOUND",
			0, // "TANGIBLE_GP0__BEAT_NORMAL",
			0, // "TANGIBLE_GP0__BEAT_BOOST",
			1, // "TANGIBLE_GP0__FLYWHEEL_NORMAL",
			0, // "TANGIBLE_GP0__FLYWHEEL_BOOST",
		},
		{ // Boost
			0, // "TANGIBLE_GP0__NOSOUND",
			0, // "TANGIBLE_GP0__SOUND",
			0, // "TANGIBLE_GP0__BEAT_NORMAL",
			0, // "TANGIBLE_GP0__BEAT_BOOST",
			0, // "TANGIBLE_GP0__FLYWHEEL_NORMAL",
			1, // "TANGIBLE_GP0__FLYWHEEL_BOOST",
		},
	},
	// STATE_FLYWHEEL_DROP,
	{
	},
};

static const int W_BlockGrouping_InTangible[NUM_STATES][NUM_BOOSTMODE][NUM_GROUPTYPES_INTANGIBLE] = {
	// STATE_NOSOUND,
	{
		{ // Normal
			1, // "GP0__NOSOUND_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__SOUND_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__SOUND_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__SOUND_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__SOUND_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP0__BEAT_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__BEAT_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__BEAT_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__BEAT_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP0__FLYWHEEL_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__FLYWHEEL_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__FLYWHEEL_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__FLYWHEEL_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP1__SOUND_BOOST"	,
			0, // "GP1__BEAT_NORMAL"	,
			0, // "GP1__FLYWHEEL_NORMAL"	,
			0, // "GP1__FLYWHEEL_BOOST__RGB"	,
			0, // "GP1__FLYWHEEL_BOOST__W"	,
			0, // "GP2__SOUND_BOOST"	,
			0, // "GP2__FLYWHEEL_NORMAL"	,
			0, // "GP2__FLYWHEEL_BOOST__RGB"	,
			0, // "GP2__FLYWHEEL_BOOST__W"	,
		},
		{ // Boost
		},
	},
	// STATE_SOUND,
	{
		{ // Normal
			0, // "GP0__NOSOUND_NORMAL__SEPARATE__SYMMETRY"	,
			1, // "GP0__SOUND_NORMAL__SEPARATE__DIRECTION"	,
			1, // "GP0__SOUND_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__SOUND_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__SOUND_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP0__BEAT_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__BEAT_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__BEAT_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__BEAT_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP0__FLYWHEEL_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__FLYWHEEL_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__FLYWHEEL_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__FLYWHEEL_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP1__SOUND_BOOST"	,
			0, // "GP1__BEAT_NORMAL"	,
			0, // "GP1__FLYWHEEL_NORMAL"	,
			0, // "GP1__FLYWHEEL_BOOST__RGB"	,
			0, // "GP1__FLYWHEEL_BOOST__W"	,
			0, // "GP2__SOUND_BOOST"	,
			0, // "GP2__FLYWHEEL_NORMAL"	,
			0, // "GP2__FLYWHEEL_BOOST__RGB"	,
			0, // "GP2__FLYWHEEL_BOOST__W"	,
		},
		{ // Boost
			0, // "GP0__NOSOUND_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__SOUND_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__SOUND_NORMAL__SEPARATE__SYMMETRY"	,
			5, // "GP0__SOUND_BOOST__SEPARATE__DIRECTION"	,
			5, // "GP0__SOUND_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP0__BEAT_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__BEAT_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__BEAT_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__BEAT_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP0__FLYWHEEL_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__FLYWHEEL_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__FLYWHEEL_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__FLYWHEEL_BOOST__SEPARATE__SYMMETRY"	,
			1, // "GP1__SOUND_BOOST"	,
			0, // "GP1__BEAT_NORMAL"	,
			0, // "GP1__FLYWHEEL_NORMAL"	,
			0, // "GP1__FLYWHEEL_BOOST__RGB"	,
			0, // "GP1__FLYWHEEL_BOOST__W"	,
			1, // "GP2__SOUND_BOOST"	,
			0, // "GP2__FLYWHEEL_NORMAL"	,
			0, // "GP2__FLYWHEEL_BOOST__RGB"	,
			0, // "GP2__FLYWHEEL_BOOST__W"	,
		},
	},
	// STATE_SOUND_DROP,
	{
	},
	// STATE_BEAT_IN,
	{
		{ // Normal
			0, // "GP0__NOSOUND_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__SOUND_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__SOUND_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__SOUND_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__SOUND_BOOST__SEPARATE__SYMMETRY"	,
			3, // "GP0__BEAT_NORMAL__SEPARATE__DIRECTION"	,
			3, // "GP0__BEAT_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__BEAT_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__BEAT_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP0__FLYWHEEL_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__FLYWHEEL_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__FLYWHEEL_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__FLYWHEEL_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP1__SOUND_BOOST"	,
			1, // "GP1__BEAT_NORMAL"	,
			0, // "GP1__FLYWHEEL_NORMAL"	,
			0, // "GP1__FLYWHEEL_BOOST__RGB"	,
			0, // "GP1__FLYWHEEL_BOOST__W"	,
			0, // "GP2__SOUND_BOOST"	,
			0, // "GP2__FLYWHEEL_NORMAL"	,
			0, // "GP2__FLYWHEEL_BOOST__RGB"	,
			0, // "GP2__FLYWHEEL_BOOST__W"	,
		},
		{ // Boost
			0, // "GP0__NOSOUND_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__SOUND_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__SOUND_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__SOUND_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__SOUND_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP0__BEAT_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__BEAT_NORMAL__SEPARATE__SYMMETRY"	,
			1, // "GP0__BEAT_BOOST__SEPARATE__DIRECTION"	,
			1, // "GP0__BEAT_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP0__FLYWHEEL_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__FLYWHEEL_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__FLYWHEEL_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__FLYWHEEL_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP1__SOUND_BOOST"	,
			0, // "GP1__BEAT_NORMAL"	,
			0, // "GP1__FLYWHEEL_NORMAL"	,
			0, // "GP1__FLYWHEEL_BOOST__RGB"	,
			0, // "GP1__FLYWHEEL_BOOST__W"	,
			0, // "GP2__SOUND_BOOST"	,
			0, // "GP2__FLYWHEEL_NORMAL"	,
			0, // "GP2__FLYWHEEL_BOOST__RGB"	,
			0, // "GP2__FLYWHEEL_BOOST__W"	,
		},
	},
	// STATE_BEAT_IN_DROP,
	{
	},
	// STATE_FLYWHEEL,
	{
		{ // Normal
			0, // "GP0__NOSOUND_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__SOUND_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__SOUND_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__SOUND_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__SOUND_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP0__BEAT_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__BEAT_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__BEAT_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__BEAT_BOOST__SEPARATE__SYMMETRY"	,
			10, // "GP0__FLYWHEEL_NORMAL__SEPARATE__DIRECTION"	,
			10, // "GP0__FLYWHEEL_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__FLYWHEEL_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__FLYWHEEL_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP1__SOUND_BOOST"	,
			0, // "GP1__BEAT_NORMAL"	,
			1, // "GP1__FLYWHEEL_NORMAL"	,
			0, // "GP1__FLYWHEEL_BOOST__RGB"	,
			0, // "GP1__FLYWHEEL_BOOST__W"	,
			0, // "GP2__SOUND_BOOST"	,
			1, // "GP2__FLYWHEEL_NORMAL"	,
			0, // "GP2__FLYWHEEL_BOOST__RGB"	,
			0, // "GP2__FLYWHEEL_BOOST__W"	,
		},
		{ // Boost
			0, // "GP0__NOSOUND_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__SOUND_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__SOUND_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__SOUND_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__SOUND_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP0__BEAT_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__BEAT_NORMAL__SEPARATE__SYMMETRY"	,
			0, // "GP0__BEAT_BOOST__SEPARATE__DIRECTION"	,
			0, // "GP0__BEAT_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP0__FLYWHEEL_NORMAL__SEPARATE__DIRECTION"	,
			0, // "GP0__FLYWHEEL_NORMAL__SEPARATE__SYMMETRY"	,
			10, // "GP0__FLYWHEEL_BOOST__SEPARATE__DIRECTION"	,
			10, // "GP0__FLYWHEEL_BOOST__SEPARATE__SYMMETRY"	,
			0, // "GP1__SOUND_BOOST"	,
			0, // "GP1__BEAT_NORMAL"	,
			0, // "GP1__FLYWHEEL_NORMAL"	,
			1, // "GP1__FLYWHEEL_BOOST__RGB"	,
			1, // "GP1__FLYWHEEL_BOOST__W"	,
			0, // "GP2__SOUND_BOOST"	,
			0, // "GP2__FLYWHEEL_NORMAL"	,
			1, // "GP2__FLYWHEEL_BOOST__RGB"	,
			1, // "GP2__FLYWHEEL_BOOST__W"	,
		},
	},
	// STATE_FLYWHEEL_DROP,
	{
	},
};

/************************************************************************************************************************/
} // namespace SPACE_LIGHT{

